run:
	@echo ""
	@echo "========== RUNNING [ bounded-producers-consumers ] =========="
	@echo ""
	./bounded-producers-consumers
	@echo ""
compile:
	@echo ""
	@echo "========== COMPILING [ bounded-producers-consumers.cpp ] =========="
	@echo ""
	g++ -std=c++20 bounded-producers-consumers.cpp -pthread -o bounded-producers-consumers
	@echo ""
	@echo ""
edit:
	@vim threadSync.cpp
all:
	@echo ""
	@echo "========== COMPILING [ bounded-producers-consumers.cpp ] =========="
	@echo ""
	g++ -std=c++20 bounded-producers-consumers.cpp -pthread -o bounded-producers-consumers
	@echo ""
	@echo "========== RUNNING [ bounded-producers-consumers ] =========="
	@echo ""
	./bounded-producers-consumers
	@echo ""
