run:
	@echo ""
	@echo "========== RUNNING [ producers-consumers ] =========="
	@echo ""
	./producers-consumers
	@echo ""
compile:
	@echo ""
	@echo "========== COMPILING [ producers-consumers.cpp ] =========="
	@echo ""
	g++ -std=c++20 producers-consumers.cpp -pthread -o producers-consumers
	@echo ""
	@echo ""
edit:
	@vim threadSync.cpp
all:
	@echo ""
	@echo "========== COMPILING [ producers-consumers.cpp ] =========="
	@echo ""
	g++ -std=c++20 producers-consumers.cpp -pthread -o producers-consumers
	@echo ""
	@echo "========== RUNNING [ producers-consumers ] =========="
	@echo ""
	./producers-consumers
	@echo ""
