run:
	@echo ""
	@echo "========== RUNNING [ readers-writers ] =========="
	@echo ""
	./readers-writers
	@echo ""
compile:
	@echo ""
	@echo "========== COMPILING [ readers-writers.cpp ] =========="
	@echo ""
	g++ -std=c++20 readers-writers.cpp -pthread -o readers-writers
	@echo ""
	@echo ""
edit:
	@vim threadSync.cpp
all:
	@echo ""
	@echo "========== COMPILING [ readers-writers.cpp ] =========="
	@echo ""
	g++ -std=c++20 readers-writers.cpp -pthread -o readers-writers
	@echo ""
	@echo "========== RUNNING [ readers-writers ] =========="
	@echo ""
	./readers-writers
	@echo ""
