run:
	@echo ""
	@echo "========== RUNNING [ dining-philosophers ] =========="
	@echo ""
	./dining-philosophers
	@echo ""
compile:
	@echo ""
	@echo "========== COMPILING [ dining-philosophers.cpp ] =========="
	@echo ""
	g++ -std=c++20 dining-philosophers.cpp -pthread -o dining-philosophers
	@echo ""
	@echo ""
edit:
	@vim threadSync.cpp
all:
	@echo ""
	@echo "========== COMPILING [ dining-philosophers.cpp ] =========="
	@echo ""
	g++ -std=c++20 dining-philosophers.cpp -pthread -o dining-philosophers
	@echo ""
	@echo "========== RUNNING [ dining-philosophers ] =========="
	@echo ""
	./dining-philosophers
	@echo ""
