run:
	@echo ""
	@echo "========== RUNNING [ thread-barrier ] =========="
	@echo ""
	./thread-barrier
	@echo ""
compile:
	@echo ""
	@echo "========== COMPILING [ thread-barrier.cpp ] =========="
	@echo ""
	g++ -std=c++20 thread-barrier.cpp -pthread -o thread-barrier
	@echo ""
	@echo ""
edit:
	@vim threadSync.cpp
all:
	@echo ""
	@echo "========== COMPILING [ thread-barrier.cpp ] =========="
	@echo ""
	g++ -std=c++20 thread-barrier.cpp -pthread -o thread-barrier
	@echo ""
	@echo "========== RUNNING [ thread-barrier ] =========="
	@echo ""
	./thread-barrier
	@echo ""
