run:
	@echo ""
	@echo "========== RUNNING [ mutual-exclusion ] =========="
	@echo ""
	./mutual-exclusion
	@echo ""
compile:
	@echo ""
	@echo "========== COMPILING [ mutual-exclusion.cpp ] =========="
	@echo ""
	g++ -std=c++20 mutual-exclusion.cpp -pthread -o mutual-exclusion
	@echo ""
	@echo ""
edit:
	@vim threadSync.cpp
all:
	@echo ""
	@echo "========== COMPILING [ mutual-exclusion.cpp ] =========="
	@echo ""
	g++ -std=c++20 mutual-exclusion.cpp -pthread -o mutual-exclusion
	@echo ""
	@echo "========== RUNNING [ mutual-exclusion ] =========="
	@echo ""
	./mutual-exclusion
	@echo ""
